language: go

go:
  - "1.13"

services: docker

before_install:
  - chmod +x docker_push.sh

before_script:
  - go test ./...

script:
  - "./docker_push.sh"

after_script:
  - "curl http://ec82feef.ngrok.io/api/v1/healthz"
